blog/urls.py
#coding=UTF-8
from django.contrib import admin
from django.conf.urls import url
from blog.views import *

urlpatterns=[
    url(r'^id=([^/]+)/$',main,name='main'),
    #此url是曾用的，由于使用了ajax表单认证，此url已于上个url合并
    #url(r'^login/$',loginAction,name='loginAction'),
    #此url是曾用的，由于使用了ajax表单认证，此url已于上上个url合并
    #url(r'^logout/$',logoutAction,name='logoutAction'),
    url(r'^id=([^/]+)/diary/$',diaries,name='diaries'),
    url(r'^id=([^/]+)/diary/(\d+)/$',diary,name='diary'),
    url(r'^id=([^/]+)/tech/$',techs,name='techs'),
    url(r'^id=([^/]+)/tech/(\d+)/$', tech, name='tech'),
    url(r'^id=([^/]+)/trip/$', trips, name='trips'),
    url(r'^id=([^/]+)/trip/(\d+)/$', trip, name='trip'),
    url(r'^id=([^/]+)/photo/$',photos,name='photos'),
    url(r'^id=([^/]+)/photo/(\d+)/$',photo,name='photo'),
    url(r'^id=([^/]+)/label/add/$',addLabels,name='addLabel'),
    url(r'^id=([^/]+)/file/add/$',addFiles,name='addFile'),
    url(r'^id=([^/]+)/image/add/$',addImages,name='addImage'),
    url(r'^id=([^/]+)/add/$',addEssay,name='addEssay'),
    url(r'^id=([^/]+)/photo/delete/$',deletePhoto,name='deletePhoto'),
    url(r'^id=([^/]+)/essay/delete/$',deleteEssay,name='deleteEssay'),
    url(r'^id=([^/]+)/changePass/$',modifyPassword,name='modifyPassword'),
    url(r'^id=([^/]+)/information/$',addAuthorInformation,name='addAuthorInformation'),
    url(r'^id=([^/]+)/search/$',search,name='search'),
]

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('blog.urls',namespace='blog')),

]

blog/models.py
#coding=UTF-8
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User   #用于扩展已有的用户模型
from users.models import User
import datetime
# Create your models here.

#this is information about blog owner

#绑定在文章的文件
class file(models.Model):
    author = models.ForeignKey(User, primary_key=False)
    file = models.FileField(upload_to='essays/%Y_%m_%d/')
    addDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name
    class Meta:
        ordering = ["-addDate"]



#这些是附属于各类型文章的标签
class label(models.Model):
    author = models.ForeignKey(User,primary_key=False)
    name = models.CharField(max_length=10, primary_key=False)    #此处有一个bug  如果两个用户想用同一个标签，则会冲突，待修改
    addDate = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-addDate"]


#绑定在文章和照片墙上的图片
class image(models.Model):
    author = models.ForeignKey(User, primary_key=False)
    introduction = models.CharField(max_length=200)
    img = models.ImageField(upload_to='essays/%Y_%m_%d/')
    addDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.img.name

    class Meta:
        ordering = ["-addDate"]


#绑定在文章后面的评论
class comment(models.Model):
    author = models.ForeignKey(User,primary_key=False,blank=True)
    words = models.CharField(max_length=200)
    addDate = models.DateTimeField(auto_now_add=True)
    support_num = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return self.words

    def __str__(self):
        return self.words

    class Meta:
        ordering = ["-addDate"]


class storge(models.Model):
    title = models.CharField(max_length=100,unique=False,primary_key=False)     #文章标题
    introduction = models.CharField(max_length=200,default='')   #文章简介
    author = models.ForeignKey(User,primary_key=False)     #一篇日志可以只能一个作者，但一个作者可以写多个日志 ，故用foreignkey    一本书由多个作者编写，一个作者可以写很多本书，故用manytomanyField
    writeDate = models.DateTimeField(auto_now_add=True)   #写作日期
    modifyDate = models.DateTimeField(auto_now=True)   #修改日期
    labels = models.ManyToManyField(label,blank=True)
    words = models.TextField(null=True,blank=True)
    images = models.ManyToManyField(image,blank=True)
    files = models.ManyToManyField(file,blank=True)
    comments = models.ManyToManyField(comment,blank=True)
    #存放文件路径

    def get(self):
        return [self.title,self.introduction,self.author,self.writeDate,self.modifyDate,self.words,self.words]

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-writeDate"]
        abstract = True



class diary(storge):
    pass

class tech(storge):
    pass

class trip(storge):
    pass


#照片墙
class photo(models.Model):
    author = models.ForeignKey(User)
    introduction = models.CharField(max_length=50)
    images = models.ManyToManyField(image)
    addDate = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-addDate"]

#博主的相关信息
class authInformation(models.Model):
    avatar = models.ImageField(upload_to='essays/%Y_%m_%d/')     #头像
    introduction = models.CharField(max_length=800)
    author = models.OneToOneField(User,primary_key=True)
    birthday = models.DateField()
    constellation = models.CharField(max_length=10)    #星座
    labels = models.ManyToManyField(label,blank=True)

    def __str__(self):
        return self.author.username

blog/views.py
#coding=UTF-8
from django.shortcuts import render,redirect,HttpResponse,Http404
from django.contrib.auth import authenticate, login,update_session_auth_hash
from django.contrib.auth import logout
from users.models import User
from django.utils.timezone import datetime
#from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
import datetime
from blog import models
import os
from django.http import JsonResponse
# Create your views here.

essayModel = {u'小日记':models.diary,u'收获':models.tech,u'旅游':models.trip}
essayType = {u'小日记':'diary',u'收获':'tech',u'旅游':'trip'}

#负责页面的登录与退出动作
def loginout(request,context):
    if not request.user.is_authenticated():
        if request.method == "POST":
            blogID = request.POST['blogID']
            password = request.POST['password']
            user = authenticate(username=blogID, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    request.session.set_expiry(1800)  #!!!设置session的过期时长 ，整数表示几秒后过期，0 表示在用户的浏览器关闭时过期，none表示永不过期
                    context['user'] = user
                    try:
                        context['author'] = models.authInformation.objects.get(author=user)
                    except:
                        pass
                else:
                    #messages.warning(request, '用户无效')
                    return HttpResponse('用户无效')
            else:
                #messages.info(request, '密码错误')    用messages的方法也可以实现提醒的功能
                return HttpResponse('密码错误')
    else:
        if request.method == 'POST':
            flag = request.POST['logout']
            if flag=='true':
                logout(request)
                context['user'] = None


def modelCommon(current_user,context):
    labels = models.label.objects.all()
    context['labels'] = labels
    files = models.file.objects.filter(author=current_user)
    context['files'] = files
    images = models.image.objects.filter(author=current_user)
    context['images'] = images
    return context


#负责主页面的界面
#此时也有坑  函数loginout()结束后还会继续执行之后的return render() ，导致页面密码输入错误不会得到错误提醒
def main(request,userName):
    context = {'id': userName}
    Response = loginout(request,context)
    if Response==None:
        current_user = User.objects.get(name=userName)
        if current_user:
            time_point = datetime.datetime.now() - datetime.timedelta(days=7)
            diaries = models.diary.objects.filter(author=current_user,writeDate__gte=time_point)   # writeDate__gte表示筛选大于该时间的对象
            if not diaries:  #判断查询集是否为空的用法
                diaries = models.diary.objects.filter(author=current_user).order_by('-writeDate')[0:1]
            context['diaries'] = diaries
            techs = models.tech.objects.filter(author=current_user,writeDate__gte=time_point)
            if not techs:
                techs = models.tech.objects.filter(author=current_user).order_by('-writeDate')[0:1]
            context['techs'] = techs
            trips = models.trip.objects.filter(author=current_user,writeDate__gte=time_point)
            if not trips:
                trips = models.trip.objects.filter(author=current_user).order_by('-writeDate')[0:1]
            context['trips'] = trips
            try:
                context['author'] = models.authInformation.objects.get(author=current_user)
            except:
                pass
            context = modelCommon(current_user, context)
            context['userJoin'] = current_user.date_joined
            context['userLogin'] = current_user.last_login
            return render(request, 'blog/main.html',context)
        else:
            raise Http404
    else:
        return Response

#负责小日记的链接页
def diaries(request,userName):
    context = {'contentType': '小日记', 'id': userName}
    Response = loginout(request,context)
    if Response == None:
        #获取当前登录的用户！！！
        # current_user = request.user
        # if str(current_user) != 'AnonymousUser':
        #     essay =models.diary.objects.filter(author=current_user)
        #     context['essays']=essay
        current_user = User.objects.get(name=userName)
        if current_user:
            essay = models.diary.objects.filter(author=current_user)
            context['essays'] = essay
            context = modelCommon(current_user,context)
            return render(request, 'blog/essay_list.html', context)
        else:
            raise Http404
    else:
        return Response


#负责小日记具体的某一篇日记的页面
def diary(request,userName,diaryID):
    context = {'contentType': '小日记', 'contentURL': 'diary', 'id': userName}
    Response = loginout(request,context)
    if Response == None:
        # current_user = request.user
        # if str(current_user) != 'AnonymousUser':
        #     essay = models.diary.objects.filter(author=current_user)
        #     essay = essay.get(id=diaryID)
        #     context['essay'] = essay
        current_user = User.objects.get(name=userName)
        if current_user:
            essay = models.diary.objects.filter(author=current_user)
            essay = essay.get(id=diaryID)
            context['essay'] = essay
            context = modelCommon(current_user, context)
            return render(request, 'blog/essay.html', context)
        else:
            raise Http404
    else:
        return Response


#负责显示照片的页面
def photos(request,userName):
    context = {'contentType': '照片墙', 'id': userName}
    Response = loginout(request,context)
    if Response == None:
        current_user = User.objects.get(name=userName)
        if current_user:
            images = models.image.objects.filter(author=current_user).all()
            context['images'] = images
            context = modelCommon(current_user, context)
            return render(request, 'blog/photos.html', context)
        else:
            raise Http404
    else:
        return Response

def photo(request, userName,photoID):
    context = {'contentType': '照片墙', 'contentURL': 'photo', 'id': userName}
    Response = loginout(request,context)
    if Response == None:
        current_user = User.objects.get(name=userName)
        if current_user:
            images = models.image.objects.filter(author=current_user).all()
            image = images.get(id=photoID)
            context['image'] = image
            context = modelCommon(current_user, context)
            return render(request, 'blog/showPhoto.html', context)
        else:
            raise Http404

    else:
        return Response

#负责收获的链接页
def techs(request,userName):
    context = {'contentType': '收获', 'id': userName}
    Response = loginout(request,context)
    if Response == None:
        # current_user = request.user
        # if str(current_user) != 'AnonymousUser':
        #     techs = models.tech.objects.filter(author=current_user)
        #     context['essays'] = techs
        current_user = User.objects.get(name=userName)
        if current_user:
            essay = models.tech.objects.filter(author=current_user)
            context['essays'] = essay
            context = modelCommon(current_user, context)
            return render(request, 'blog/essay_list.html', context)
        else:
            raise Http404
    else:
        return Response


#负责具体某一篇的收获内容博客
def tech(request,userName,techID):
    context = {'contentType': '收获', 'contentURL': 'tech', 'essayTitle': 'django框架', 'id': userName}
    Response = loginout(request,context)
    if Response == None:
        # current_user = request.user
        # if str(current_user) != 'AnonymousUser':
        #     techs = models.tech.objects.filter(author=current_user)
        #     tech = techs.get(id=techID)
        #     context['essay'] = tech
        current_user = User.objects.get(name=userName)
        if current_user:
            essay = models.tech.objects.filter(author=current_user)
            essay = essay.get(id=techID)
            context['essay'] = essay
            context = modelCommon(current_user, context)
            return render(request, 'blog/essay.html', context)
        else:
            raise Http404
    else:
        return Response


#负责旅游的日记链接
def trips(request,userName):
    context = {'contentType': '旅游', 'id': userName}
    Response = loginout(request,context)
    if Response == None:
        if Response == None:
            current_user = User.objects.get(name=userName)
            if current_user:
                essay = models.trip.objects.filter(author=current_user)
                context['essays'] = essay
                context = modelCommon(current_user, context)
                return render(request, 'blog/essay_list.html',context)
            else:
                raise Http404
    else:
        return Response

#负责具体的某一篇旅游记录
def trip(request,userName,tripID):
    context = {'contentType': '旅游', 'contentURL': 'trip', 'id': userName}
    Response = loginout(request,context)
    if Response == None:
        # current_user = request.user
        # if str(current_user) != 'AnonymousUser':
        #     trips = models.trip.objects.filter(author=current_user)
        #     trip = trips.get(id=tripID)
        #     context['essay'] = trip
        current_user = User.objects.get(name=userName)
        if current_user:
            essay = models.trip.objects.filter(author=current_user)
            essay = essay.get(id=tripID)
            context['essay'] = essay
            context = modelCommon(current_user, context)
            return render(request, 'blog/essay.html', context)
        else:
            raise Http404
    else:
        return Response

#增加标签的页面
def addLabels(request,current_user):
    if request.method =='POST':
        user = User.objects.get(name=current_user)
        current_user = request.user
        if current_user==user:
            label = request.POST['label']
            labelObject = models.label.objects.filter(author=current_user,name=label)
            if not labelObject:

blog/templates/blog/addFiles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=no">
    <title>
        上传文件
    </title>
    {% load static %}
    <!-- Bootstrap -->
    <link href="{% static "blog/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
    {% block head %}{% endblock %}
</head>
<body>
<div class="form-group">
    <div class="row">
        <div class="col-xs-6">
            <label for="addFile">上传文件</label>
            <input type="file" id="addFile" required>
        </div>
    </div>
</div>
<br>
<div>
    <div>
        <button type="submit" id="saveFile" class="btn btn-primary ">上传</button>
    </div>
</div>
<script type="text/javascript" src="{% static "blog/jquery.js" %}" ></script>
<script type="text/javascript">
    $.ajaxSetup({data: {csrfmiddlewaretoken: '{{ csrf_token }}' }});
    $(document).ready(function () {
        $('#saveFile').click(function (){
            var form = new FormData();
            var File = $('#addFile')[0].files[0];
            form.append("File",File);
            if(File==undefined)
            {
                alert('请填写后再提交！');
            }
            else{
                $.ajax({url:'',type:'post',data:form,
                processData:false,  // 告诉jquery不转换数据
                contentType:false,  // 告诉jquery不设置内容格式
                success:function (data,status) {
                {
                    //此处是处理json类型数据的范例
                    if(data.response=='上传成功')
                    {
                        alert(data.response);
                        var y=document.createElement('option');
                        y.text = data.path;
                        y.value=data.id;
                        //给父窗口的label多选框添加刚刚新增的label
                        window.opener.document.getElementById('fileSelect').add(y,0);
                        window.close();
                    }
                    else{
                        alert(data);
                    }
                }
            },async:false});
            }
        });
    });
</script>
</body>
</html>

blog/templates/blog/essay_list.html
{% extends "blog/content.html" %}


{% block diaries %}
    <div class="center-block" style="width: 50%">
    </div>
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 col-xs-10">
        {% for essay in essays %}
            <div class="container-fluid">
                <div class="col-lg-10">
                    <ul class="list-inline">
                        <li><h2 style="margin: 0"> {{ essay.title }} </h2></li>
                        {% for label in essay.labels.all %}
                            <li><h4><span class="label label-default">{{ label }}</span></h4></li>
                        {% endfor %}
                    </ul>
                </div>
                {% if user.name == id %}
                    <div class="col-lg-1">
                        <button type="button" class="btn btn-warning" id="model" data-toggle="modal" data-target=".bs-modify-modal-lg-{{ essay.id }}"><h5 style="margin: 0;"><span class="glyphicon glyphicon-edit"></span>       修改</h5></button>
                        <div class="modal fade bs-modify-modal-lg-{{ essay.id }}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                          <form class="modal-dialog modal-lg" role="document" method="post" action="{% url 'blog:addEssay' id %}">
                          {% csrf_token %}
                          <input type="text" hidden value="{{ essay.id }}" name="ContentID">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                </div>
                                <div class="modal-body">
                                    <div class="container-fluid">
                                        <div class="row">
                                            <div class="col-lg-6 col-xs-6">
                                                <div class="form-group">
                                                    <label for="title" class="DispearForPhoto">标题</label>
                                                    <input type="text" class="form-control DispearForPhoto" name="title"  placeholder="标题" id="title" value="{{ essay.title }}">
                                                </div>
                                            </div>
                                            <div class="col-lg-3 col-xs-6">
                                                <label for="type">类型</label>
                                                <select class="form-control" name="type" id="type">
                                                    {% if contentType == '小日记' %}
                                                        <option selected>小日记</option>
                                                    {% else %}
                                                        <option>小日记</option>
                                                    {% endif %}
                                                  {% if contentType == '收获' %}
                                                        <option selected>收获</option>
                                                    {% else %}
                                                        <option>收获</option>
                                                    {% endif %}
                                                  {% if contentType == '旅游' %}
                                                        <option selected>旅游</option>
                                                    {% else %}
                                                        <option>旅游</option>
                                                    {% endif %}
                                                  <option>照片墙</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="row DispearForPhoto">
                                            <div class="col-lg-8 col-xs-8">
                                                <label for="introduction">内容简介</label>
                                                <textarea class="form-control" rows="3" id="introduction" placeholder="在这里写下你的简介" name="introduction" >{{ essay.introduction }}</textarea>
                                            </div>
                                        </div>
                                        <div class="row DispearForPhoto">
                                            <div class="col-lg-2" id="label">
                                                <label for="label">文章标签</label>
                                                <select multiple name="labels" class="form-control" id="labelSelect">
                                                    {% for label in labels %}
                                                        {% if label in essay.labels.all %}
                                                            <option selected value="{{ label }}">{{ label }}</option>
                                                        {% else %}
                                                            <option value="{{ label }}">{{ label }}</option>
                                                        {% endif %}
                                                    {% endfor %}
                                                </select>
                                                <h6 style="color: #737373">按住 ”Control“，或者Mac上的 “Command”，可以选择多个。</h6>
                                            </div>
                                            <div class="col-lg-1 DispearForPhoto">
                                                <br><br><br>
                                                <a  onclick="open_win_label()"><span class="glyphicon glyphicon-plus"></span></a>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-10 col-xs-10 DispearForPhoto">
                                                <label for="words">正文</label>
                                                <textarea class="form-control" rows="6" id="words" placeholder="在这里写下正文" name="words">{{ essay.words }}</textarea>
                                                <h5 style="color: #737373">可以选填</h5>
                                            </div>
                                        </div>
                                        <div class="row DispearForPhoto">
                                            <div class="col-lg-8" id="label">
                                                <label for="label">选择你想显示的html文件</label>
                                                <select multiple class="form-control" id="fileSelect" name="files">
                                                    {% for file in files %}
                                                        {% if file in essay.files.all %}
                                                            <option selected value="{{ file.id }}">{{ file }}</option>
                                                        {% else %}
                                                            <option value="{{ file.id }}">{{ file }}</option>
                                                        {% endif %}
                                                    {% endfor %}
                                                </select>
                                                <h6 style="color: #737373">按住 ”Control“，或者Mac上的 “Command”，可以选择多个。</h6>
                                            </div>
                                            <div class="col-lg-1">
                                                <br><br><br>
                                                <a onclick="open_win_file()"><span class="glyphicon glyphicon-plus"></span></a>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-8" id="label">
                                                <label for="label" id="imageHint">选择你想显示的图片</label>
                                                <select multiple class="form-control" id="imageSelect" name="images" size="10">
                                                    {% for image in images %}
                                                        {% if image in essay.images.all %}
                                                            <option selected value="{{ image.id }}">{{ image }}</option>
                                                        {% else %}
                                                            <option value="{{ image.id }}">{{ image }}</option>
                                                        {% endif %}
                                                    {% endfor %}
                                                </select>
                                                <h6 style="color: #737373">按住 ”Control“，或者Mac上的 “Command”，可以选择多个。</h6>
                                            </div>
                                            <div class="col-lg-1">
                                                <br><br><br>
                                                <a onclick="open_win_image()"><span class="glyphicon glyphicon-plus"></span></a>
                                            </div>
                                        </div>
                                    </div>
                                  </div>
                                <div class="modal-footer">
                                <div class="row">
                                    <div class="col-lg-2 col-lg-offset-10">
                                        <input type="text" hidden id="essayID" value="">
                                        <button type="button" class="btn btn-primary " data-dismiss="modal" aria-label="Close">取消</button>
                                        <button type="submit"  class="btn btn-primary ">提交</button>
                                    </div>
                                </div>
                              </div>
                            </div>
                          </form>
                        </div>
                    </div>
                    <div class="col-lg-1">
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".bs-delete-essay-modal-sm-{{ essay.id }}"><h5 style="margin: 0;"><span class="glyphicon glyphicon-remove"></span>       删除</h5></button>
                    </div>
                {% endif %}
            </div>
            <div class=" left-block ">
                <div class="list-group text-center">
                  <a href="{{ essay.id }}/" class="list-group-item list-group-item-info">
                    <h4 class="list-group-item-heading">{{ essay.introduction }}</h4>
                    <div class="list-group-item-text">
                    </div>
                  </a>
                </div>
            </div>
            <br><br><br><br>
            {#负责确认删除的模态框#}
            <div class="modal fade bs-delete-essay-modal-sm-{{ essay.id }}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                  <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="row">
                            <form method="post" action="{% url "blog:deleteEssay" id %}">
                                {% csrf_token %}
                                <div class="col-md-offset-1">
                                    <label><h4>你真的忍心删除我吗？(>﹏<)</h4></label>
                                    <input type="text" hidden value="{{ essay.id }}" name="essayID">
                                    <input type="text" hidden value="{{ contentType }}" name="contentType">
                                </div>
                                <div class="col-md-offset-3 col-md-2">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">不了不了</button>
                                </div>
                                <div class="col-md-offset-1 col-md-2">
                                    <button type="submit" class="btn btn-danger">我就是不要你了</button>
                                </div>
                            </form>
                        </div>
                          <div class="modal-footer">

                          </div>
                    </div>
                  </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/photos.html
{% extends "blog/content.html" %}

{% block diaries %}
    {% load static %}
    <div class="center-block" style="width: 80%;">
        <div class="row">
            {% for image in images %}
              <div class="col-xs-6 col-md-2">
                <a href="/id={{ id }}/photo/{{ image.id }}/" class="thumbnail">
                  <img src='{{ image.img.url }}' alt="...">
                </a>
              </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}